### ISSUE TITLE
STL for the left hand

### ISSUE THREAD

**Issue by fi0** [foochbwah/crkbd-case#2]
Flipping the right hand model doesn't work, because the position of the TRRS jacks are not the same. 
Do you have an STL for the left hand case please? thank you!

**Comment by foochbwah** [comment]
i'm not sure what to tell you; the position of the trrs jacks should be the same. the case design is based on foostan's original pcb design, which is reversible, and i built the keyboard in the picture by mirroring the right side file in the printer. in any case, the source file for the case design is available should you need to modify your specific case.

**Comment by fi0** [comment]
Thank you for your reply. I found out the reason. 
The position of the TRRS jacks for crkbd-classic and crkbd-light is slightly different.
